# Generated by Django 2.2.1 on 2019-05-09 20:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombres', models.CharField(default='s', max_length=80)),
                ('pro_apellidoPaterno', models.CharField(default='s', max_length=70)),
                ('pro_apellidoMaterno', models.CharField(default='s', max_length=70)),
                ('pro_fechaNacimento', models.DateField(blank=True, default=datetime.datetime.now)),
                ('pro_nombre', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_teacher', 'Is_Teacher'),),
            },
        ),
    ]
