# Generated by Django 2.2.1 on 2019-05-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alu_nombre', models.CharField(max_length=400)),
                ('alu_genero', models.CharField(default='Masculino', max_length=10)),
                ('alu_vigente', models.BooleanField(default=True)),
                ('alu_fechaIngreso', models.DateField(auto_now_add=True, null=True)),
                ('alu_observaciones', models.CharField(max_length=2000, null=True)),
                ('alu_foto', models.ImageField(default='media/default/default.jpeg', null=True, upload_to='media/fotosAlu')),
                ('slug', models.SlugField(default='AKEEHDUAXBSQKLSRH83FV1UB', max_length=24)),
                ('alu_tutores', models.ManyToManyField(to='padres.Tutor')),
            ],
        ),
    ]
