# Generated by Django 2.0.5 on 2019-05-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20190509_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='QYNRW0K9G3372DJFKUAJY3TI', max_length=24),
        ),
    ]
