# Generated by Django 2.0.5 on 2019-05-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20190511_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='8ENTHWVBX3QBG8XQRJYJ45H1', max_length=24),
        ),
    ]
