# Generated by Django 2.0.5 on 2019-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_auto_20190511_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='RI8E11X4N8S5SIVOLY0IM6NV', max_length=24),
        ),
    ]
