# Generated by Django 2.0.5 on 2019-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_auto_20190511_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='6SBIZ04SADX1U3TJK4G0D81J', max_length=24),
        ),
    ]
