# Generated by Django 2.0.5 on 2019-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_auto_20190511_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='46CG5CLM2IUSFO4IPH5K5WWV', max_length=24),
        ),
    ]
