# Generated by Django 2.2.1 on 2019-05-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_auto_20190511_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='CB3UQ1GZPQTQAJDL9W39M57J', max_length=24),
        ),
    ]
