# Generated by Django 2.2.1 on 2019-05-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_auto_20190521_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='UFCI9QS8GLDJJFMZR43QVQ76', max_length=24),
        ),
    ]
