# Generated by Django 2.2.1 on 2019-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_auto_20190521_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='BVTJ67DXMV38DSX43LVKHK1A', max_length=24),
        ),
    ]
