# Generated by Django 2.2.1 on 2019-05-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_auto_20190523_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='HXQQAEFAN90ES1XHIZGVX4KR', max_length=24),
        ),
    ]
