# Generated by Django 2.2.1 on 2019-05-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_auto_20190523_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='R6MWT586I6SOC2Q46WH7I59E', max_length=24),
        ),
    ]
