# Generated by Django 2.2.1 on 2019-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0015_auto_20190523_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='1T6Z4UHL6BJ7AL57E4MUMLTA', max_length=24),
        ),
    ]
