# Generated by Django 2.2.1 on 2019-05-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0017_auto_20190523_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='TSWXK9DA5D5POQNLMNTOSIIH', max_length=24),
        ),
    ]
