# Generated by Django 2.2.1 on 2019-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_auto_20190524_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='KA6IKBZ3PQVKE62PK9LJEMAB', max_length=24),
        ),
    ]
