# Generated by Django 2.2.1 on 2019-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0019_auto_20190524_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='HZ2KJNTCAH4QJP99JEZAWHO4', max_length=24),
        ),
    ]
