# Generated by Django 2.2.1 on 2019-05-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0020_auto_20190524_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='slug',
            field=models.SlugField(default='KJV0LFJ3LS6SA8G62TCA2H95', max_length=24),
        ),
    ]
